# Numpy 제대로 배우기 복습
### keonwoo Park 2020/08/29

In [2]:
import numpy as np
np.__version__

'1.18.1'

## 배열 생성
### 리스트로 배열 만들기

In [18]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [5]:
a2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [6]:
a3 = np.array([[[1, 2, 3] , [4, 5, 6], [7, 8, 9]],
              [[1, 2, 3] , [4, 5, 6], [7, 8, 9]],
              [[1, 2, 3] , [4, 5, 6], [7, 8, 9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


## 배열 생성 및 초기화
- zerors(): 모든 요소를 0 으로 초기화

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones(): 모든 요소를 1로 초기화

In [9]:
print(np.ones(10))
print(np.ones((3, 3)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- full(): 모든요소를 지정한 값으로 초기화

In [10]:
np.full((3, 3), 77)

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

- eye(): 단위행렬 생성 

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- tri(): 삼각행렬 생성

In [13]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [14]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# 초기화 되지 않은 배열을 생성 한다.
# 기존 메모리 위치에 값이 존재함
np.empty((3, 3))

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [19]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [21]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
print(a3)
np.full_like(a3, 77)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[77, 77, 77],
        [77, 77, 77],
        [77, 77, 77]],

       [[77, 77, 77],
        [77, 77, 77],
        [77, 77, 77]],

       [[77, 77, 77],
        [77, 77, 77],
        [77, 77, 77]]])

## 생성한 값으로 배열 생성

In [34]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.linspace(0, 10, 6).reshape(3, 2)

array([[ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.]])

In [37]:
np.logspace(0.1, 1 , 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

## 랜덤값으로 배열 생성

In [42]:
# 랜덤한 수의 배열 생성
np.random.random((2, 2))

array([[0.14397227, 0.08825494],
       [0.56963871, 0.48078512]])

In [47]:
# 랜덤한 수의 정수 생성
np.random.randint(0, 10,(4, 3))

array([[7, 6, 1],
       [9, 0, 4],
       [2, 4, 9],
       [2, 6, 2]])

In [49]:
# 정규 분포를 고려한 배열 생성
np.random.normal(10, 3, (3, 3))

array([[12.21554722,  8.20700574, 10.60294865],
       [ 7.75095023,  6.50292751,  5.14647369],
       [11.65729927, 13.93053642, 11.04185123]])

## 표준 데이터 타입

In [51]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [53]:
np.full((4, 2), 17, dtype = float)

array([[17., 17.],
       [17., 17.],
       [17., 17.],
       [17., 17.]])

## 날짜/시간 배열

In [56]:
date = np.array("2020-01-01", dtype = np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [57]:
date + np.arange(10)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10'], dtype='datetime64[D]')

In [58]:
datetime = np.datetime64("2020-08-01 12:00")
datetime

numpy.datetime64('2020-08-01T12:00')

In [59]:
datetime = np.datetime64("2020-08-01 12:00:30.345", 'ns')
datetime

numpy.datetime64('2020-08-01T12:00:30.345000000')

## 배열조회
### 배열 속성 정보

In [60]:
def array_info(array):
    print(array)
    print("ndim", array.ndim)
    print("shape", array.shape)
    print("dtype", array.dtype)
    print("size", array.size)
    print("itemsize", array.itemsize)
    print("nbytes", array.nbytes)
    print("strides:", array.strides)

In [61]:
array_info(a1)

[4 5 6 4 5]
ndim 1
shape (5,)
dtype int32
size 5
itemsize 4
nbytes 20
strides: (4,)


In [62]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape (3, 3)
dtype int32
size 9
itemsize 4
nbytes 36
strides: (12, 4)


In [63]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim 3
shape (3, 3, 3)
dtype int32
size 27
itemsize 4
nbytes 108
strides: (36, 12, 4)


## 인덱싱

In [64]:
print(a1)
print(a1[0])
print(a1[-2])

[4 5 6 4 5]
4
4


In [65]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5


In [66]:
print(a3)
print(a3[0, 0, 1])
print(a3[2, 2, 2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
2
9


## 슬라이싱 구문

In [67]:
print(a1)
print(a1[0:2])
print(a1[1:])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[5 6 4 5]
[4 6 5]
[5 4 6 5 4]


In [72]:
print(a2)
print(a2[1])
print(a2[2, :])
print(a2[1:, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[7 8 9]
[[6 5 4]
 [9 8 7]]


## 불리언 인덱싱

In [74]:
print(a1)
bi = [False, True, False, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 4]


In [75]:
print(a2)
bi = np.random.randint(0,2 , (3, 3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [ True  True False]
 [False False False]]
[4 5]


## 펜시 인덱싱

In [77]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1],
               [2, 0]])
print(a1[ind])

[4 5 6 4 5]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [82]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]


In [80]:
print(col)

[1 2]


In [81]:
print(row)

[0 2]


## 배열 값 삽입

In [83]:
print(a1)
b1 = np.insert(a1, 0 , 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [88]:
print(a2)
b2 = np.insert(a2 , 1 , 10 , axis = 0)
print(b2)
c2 = np.insert(a2 , 1 , 10 , axis = 1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [93]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i  = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [96]:
b1 = np.delete(a2, 1 ,axis= 1)
print(b1)

[[1 3]
 [4 6]
 [7 9]]


In [100]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [119]:
print(a2)
print(a2.resize((3, 5), refcheck = False))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
None


In [112]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize(5, 2)
print(n2)

[[0 7 5 9 2]
 [7 8 2 9 3]]
[[0 7]
 [5 9]
 [2 7]
 [8 2]
 [9 3]]


In [113]:
type(n2)

numpy.ndarray