## Pandas 복습
### keonwoo Park 2020/09/01

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.0.1'

In [3]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [4]:
type(s)

pandas.core.series.Series

In [6]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s[1]

0.25

In [9]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [10]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = ['a', 'b','c', 'd','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [16]:
type(s.index)

pandas.core.indexes.base.Index

In [18]:
idx = ['a','c','d']
s[idx]

a    0.00
c    0.50
d    0.75
dtype: float64

In [19]:
'b' in s

True

In [22]:
'b' in s

True

In [29]:
s = pd.Series(np.linspace(0,1,5),
             index = [2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [27]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [33]:
s.unique

<bound method Series.unique of 2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64>

In [35]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [69]:
pop_tuple = {'서울특별시': 9720846,
             "부산광역시": 3404423,
             "인천광역시": 2947217,
             "대구광역시": 2427954,
             "대전광역시": 1471040,
             "광주광역시": 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [37]:
population["서울특별시"]

9720846

In [38]:
population["서울특별시":"대전광역시"]

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
dtype: int64

## DataFrame

In [42]:
pd.DataFrame([{"A": 2, "B": 4, "D": 3},
            {"A" : 4, "B":2, "C": 5}])

A  B    D    C
0  2  4  3.0  NaN
1  4  2  NaN  5.0

In [44]:
a = pd.DataFrame(np.random.rand(5, 5),
            columns = ["A",'B','C','D','E'],
            index = [1, 2, 3, 4, 5])

In [53]:
male_tuple = {'서울특별시': 4732275,
             "부산광역시": 1668618,
             "인천광역시": 1476813,
             "대구광역시": 1198815,
             "대전광역시": 734441,
             "광주광역시": 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [54]:
female_tuple = {'서울특별시': 4988571,
             "부산광역시": 1735805,
             "인천광역시": 1470404,
             "대구광역시": 1229139,
             "대전광역시": 736599,
             "광주광역시": 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [70]:
korea_df = pd.DataFrame({"인구수": population,
                        "남자인구": male,
                        "여자인구":female})
korea_df

인구수     남자인구     여자인구
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [74]:
df = pd.DataFrame([male, female],
                 index = ['남자인구', '여자인구']).T
df

남자인구     여자인구
서울특별시  4732275  4988571
부산광역시  1668618  1735805
인천광역시  1476813  1470404
대구광역시  1198815  1229139
대전광역시   734441   736599
광주광역시   720060   734988

In [75]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [76]:
korea_df.columns

Index(['인구수', '남자인구', '여자인구'], dtype='object')

In [78]:
korea_df["여자인구"]

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구, dtype: int64

In [79]:
korea_df["서울특별시":"인천광역시"]

인구수     남자인구     여자인구
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

## Index 객체

In [81]:
idx = pd.Index([2, 4, 6, 8, 10])

In [82]:
idx[1]

4

In [83]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [84]:
idx[-1]

10

In [86]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


In [110]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [112]:
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [113]:
s.reindex(['a','c','b', ' k','e','d','f','h','j'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [89]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [90]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [91]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [92]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [93]:
s[(s>0.4)&(s<0.8)]

c    0.50
d    0.75
dtype: float64

In [96]:
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [97]:
s[1]

0.25

In [98]:
s.iloc[1]

0.25

In [99]:
s['b']

0.25

In [104]:
s.iloc[2:4]

c    0.50
d    0.75
dtype: float64

In [107]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
             index = [1, 3, 5, 7, 9])

In [108]:
s

1    0.00
3    0.25
5    0.50
7    0.75
9    1.00
dtype: float64

In [109]:
s.reindex(range(11))

0      NaN
1     0.00
2      NaN
3     0.25
4      NaN
5     0.50
6      NaN
7     0.75
8      NaN
9     1.00
10     NaN
dtype: float64

In [114]:
korea_df

인구수     남자인구     여자인구
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [115]:
korea_df.남자인구

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구, dtype: int64

In [116]:
df

남자인구     여자인구
서울특별시  4732275  4988571
부산광역시  1668618  1735805
인천광역시  1476813  1470404
대구광역시  1198815  1229139
대전광역시   734441   736599
광주광역시   720060   734988

In [117]:
df["총 인구"] = df['남자인구']+df['여자인구']
df

남자인구     여자인구     총 인구
서울특별시  4732275  4988571  9720846
부산광역시  1668618  1735805  3404423
인천광역시  1476813  1470404  2947217
대구광역시  1198815  1229139  2427954
대전광역시   734441   736599  1471040
광주광역시   720060   734988  1455048

In [122]:
df['남여 비율'] = (df['남자인구']/df["여자인구"]) * 100

In [123]:
df

남자인구     여자인구     총 인구       남여 비율
서울특별시  4732275  4988571  9720846   94.862336
부산광역시  1668618  1735805  3404423   96.129346
인천광역시  1476813  1470404  2947217  100.435867
대구광역시  1198815  1229139  2427954   97.532907
대전광역시   734441   736599  1471040   99.707032
광주광역시   720060   734988  1455048   97.968946

In [124]:
df.values

array([[4.73227500e+06, 4.98857100e+06, 9.72084600e+06, 9.48623363e+01],
       [1.66861800e+06, 1.73580500e+06, 3.40442300e+06, 9.61293463e+01],
       [1.47681300e+06, 1.47040400e+06, 2.94721700e+06, 1.00435867e+02],
       [1.19881500e+06, 1.22913900e+06, 2.42795400e+06, 9.75329072e+01],
       [7.34441000e+05, 7.36599000e+05, 1.47104000e+06, 9.97070319e+01],
       [7.20060000e+05, 7.34988000e+05, 1.45504800e+06, 9.79689464e+01]])

In [126]:
df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [131]:
df.values[1]

array([1.66861800e+06, 1.73580500e+06, 3.40442300e+06, 9.61293463e+01])

In [133]:
df.loc[:'인천광역시', :"여자인구"]

남자인구     여자인구
서울특별시  4732275  4988571
부산광역시  1668618  1735805
인천광역시  1476813  1470404

In [134]:
df.iloc[:3,:2]

남자인구     여자인구
서울특별시  4732275  4988571
부산광역시  1668618  1735805
인천광역시  1476813  1470404

In [152]:
a= df.loc[df['남여 비율'] > 98]['총 인구']
a.unstack

method